language: node_js
node_js:
  - v12.10.0
branches:
  only:
    - master
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: ${travis_token}
  repo: JINJITING/front-end-road
  keep_history: false
  committer_from_gh: true
  on:
    branch: master