language: node_js
node_js:
  - v12.10.0
branches:
  only:
    - main
install:
  - yarn
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: ${travis_ci}
  repo: JINJITING/fe-notes
  keep_history: false
  committer_from_gh: true
  on:
    branch: main